COUCHBASE_IP=192.168.56.105
COUCHBASE_PORT=8091

CURRENT_DIR=`pwd`
MRG_SRC_PIG_RESULT_FOLDER=
MRG_SRC_FEEDBACK_RESULT_FOLDER=
BUILD_DIR=$CURRENT_DIR/../target/
DATA_DIR=$CURRENT_DIR/input/
OUTPUT_DIR=$CURRENT_DIR/output
 
